FROM bitnami/spark:3.5.3

USER root

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY stream_inference.py /opt/bitnami/spark/work/stream_inference.py
